# Generated by Django 4.2 on 2023-05-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_remove_product_categor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='var/www/wibe_temp/shop/product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='var/www/wibe_temp/shop/product/%Y/%m/%d'),
        ),
    ]
