# Generated by Django 4.0.2 on 2023-04-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_product_categor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categor',
        ),
    ]
