# Generated by Django 4.0.2 on 2023-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_b',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
